trigger:
- none

parameters:
- name: subscriptionid
  displayName: 'Subscription Id'
  type: string
  values:
    - 'c7142d9c-6420-4b6d-a608-d8b19fd4604b'
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
- name: vm_name
  displayName: 'Virtual Machine Name'
  type: string
- name: users_name
  displayName: 'Users Name'
  type: string
# - name: password
#   displayName: 'Password'
#   type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'

variables:
  - group: ${{ parameters.environment }}
  - name: keyVaultName
    value: 'devvmkv01'
jobs:
- job: RunAzureCLI
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
      
        # Set the Azure subscription
        az account set --subscription '${{parameters.subscriptionid}}'
      
        # Update password users
        az vm user update \
          --resource-group '${{parameters.resourcegroup}}' \
          --name '${{parameters.vm_name}}' \
          --username '${{parameters.users_name}}' \
          --password '$(NewPassword)'
          echo "The password change of the ${{parameters.users_name}} user was successful."

        # Create secrets in Key Vault
        az keyvault secret set \
          --name '${{parameters.vm_name}}-${{parameters.users_name}}' \
          --vault-name '$(keyVaultName)' \
          --value 'your-secret-value'

        az keyvault secret set \
          --name '${{parameters.vm_name}}-password' \
          --vault-name '$(keyVaultName)' \
          --value 'your-password'
    displayName: 'Run Command for change password user and create secrets in Key Vault'
