trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: users_name
  displayName: 'Users Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'
- name: tagsToFilter
  displayName: 'Tags to Filter'
  type: string
  default: 'owner,environment,BUILDING_BLOCK'

variables:
  - group: ${{ parameters.environment }}

jobs:
- job: RunAzureCLI
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptLocation: 'inlineScript'
      inlineScript: |
        IFS=',' read -ra users <<< "$(users_name)"
        for user in "${users[@]}"; do
          az vm run-command invoke \
              --resource-group $(resource_group) \
              --name $(vm_name) \
              --command-id RunShellScript \
              --scripts "sudo chage -l $user | grep 'Password expires' | awk -F': ' '{print \"User: $user, Password expires: \" \$2}'"
        done
    displayName: 'Execute script for validate Password expirate date'
