trigger: none

jobs:
- job: CheckPasswordExpiry
  displayName: 'Check Password Expiry'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: 'Run Azure CLI script'
    inputs:
      azureSubscription: 'all_spn'  # Reemplaza con el nombre de tu conexión de suscripción Azure
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: '$(Build.SourcesDirectory)/scripts/check_password_expiry.sh'
      arguments: 'davovero davidv'  # Reemplaza con los nombres de usuario reales
