trigger:
none

pool:
  vmImage: 'ubuntu-latest'

variables:
  usersToCheck: 'darovero'
  vmName: 'devvmlab03' # Nombre de tu máquina virtual en Azure

steps:
- task: AzureVMExtension@0
  inputs:
    azureSubscription: 'darovero-subscription'
    action: 'Run Shell Script on VMs'
    resourceGroup: 'devvmlab0_group'
    vms: '$(vmName)' # Usando la variable vmName para especificar el nombre de la VM
    scriptType: 'bash'
    scriptPath: 'script.sh' # Ruta al script bash en tu repositorio
    scriptArguments: '$(usersToCheck)' # Pasando los usuarios a verificar como argumento al script
