trigger: none

jobs:
- job: CheckPasswordExpiry
  displayName: 'Check Password Expiry'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzurePowerShell@5
    displayName: 'Azure PowerShell script'
    inputs:
      azureSubscription: 'all_spn'  # Replace 'YourAzureSubscription' with the name of your Azure subscription service connection in Azure DevOps
      ScriptType: 'FilePath'
      ScriptPath: '$(Build.SourcesDirectory)/scripts/check_password_expiry.ps1'  # Path to your PowerShell script
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true