trigger:
- none

parameters:
- name: subscriptionid
  displayName: 'Subscription Id'
  type: string
  values:
    - 'c7142d9c-6420-4b6d-a608-d8b19fd4604b'
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
  values:
    - 'devk8slab01'
- name: vm_name
  displayName: 'Virtual Machine Name'
  type: string
- name: users_name
  displayName: 'Users Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'

variables:
  - group: ${{ parameters.environment }}

jobs:
- job: ValidatePasswordExpirationTime
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
      
        # Set the Azure subscription
        az account set --subscription '${{parameters.subscriptionid}}'
        
        # Read and iterate over the users
        IFS=',' read -ra users <<< "$(echo '${{parameters.users_name}}')"
        for user in "${users[@]}"; do
          az vm run-command invoke \
              --resource-group '${{parameters.resourcegroup}}' \
              --name '${{parameters.vm_name}}' \
              --command-id RunShellScript \
              --scripts "sudo chage -l $user | grep 'Password expires' | awk -F': ' '{print \"User: $user, Password expires: \" \$2}'"
        done
    displayName: 'Run Command for one or multiple users'
