trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  usersToCheck: 'username1 username2'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ./script.sh $(echo $usersToCheck)